### ISSUE TITLE
Error: MAC Invalid in CI

### ISSUE THREAD

**Issue by achingbrain** [libp2p/js-libp2p-secio#116]
There are intermittent CI failures with this error.  What can cause it?

Example: https://travis-ci.com/ipfs/interop/jobs/286758788

```console
  1) pubsub
       publish from JS, subscribe on Go
         "before all" hook: connect for "should exchange ascii data":
     HTTPError: 
    Error: MAC Invalid: f39fb68d3b3b8804823a153d1173f29f160588d02ff8715f0a58edc437a1fe4b != 3954fc7fb2c158dce5a18a26b5042fc502dcd480ad04da8c428a8da276aed2b2
        at C:/Users/travis/build/ipfs/interop/node_modules/ipfs/node_modules/libp2p-secio/src/etm.js:33:15
      at errorHandler (node_modules\ipfs-http-client\src\lib\error-handler.js:41:17)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by jacobheun** [comment]
We've seen this intermittently in the past. This is occurring when we are reading in messages, so I am thinking this may be do to a remote reset on the stream while we're reading. Do you know if MDNS is enabled for the tests that are failing intermittently? Since this is in the `before all` hook, it could be a result of the tcp simultaneous dial issue in Go. I'm curious if both peers are attempting to dial one another, or if it's just a one way connection.

**Comment by achingbrain** [comment]
The tests use the `test: true` flag to `ipfsd-ctl` which means it uses the `test` profile so MDNS shouldn't be enabled, no.

https://github.com/ipfs/js-ipfs/blob/master/src/core/components/config.js#L75-L89
